language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3
os:
  - linux
sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PYTHON=3.3
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PYTHON=3.4
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PYTHON=3.5
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PYTHON=2.7
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PYTHON=pypy.2
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PYTHON=pypy.3

before_install:
  - sudo chmod +x .travis/install.sh && sudo chown $USER .travis/install.sh && /bin/bash .travis/install.sh

install:
  - source camsa-env/bin/activate
  - pip install -r requirements.txt
  - chmod +x camsa/utils/mummer/nucmer-to-camsa.py
  - chmod +x camsa/camsa.py

script:
  - camsa/utils/mummer/nucmer-to-camsa.py --help
  - camsa/camsa.py --help
