language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: 3.4
    - os: linux
      sudo: required
      python: 3.5
    - os: osx
      sudo: required
      language: generic
      env: PYVER=3.4
    - os: osx
      sudo: required
      language: generic
      env: PYVER=3.5

before_install: sudo ./.travis/install.sh

install:
  - source camsa-env/bin/activate
  - pip install -r requirements.txt
  - chmod +x camsa/utils/mummer/nucmer-to-camsa.py

script: camsa/utils/mummer/nucmer-to-camsa.py --help
