language: python

matrix:
  include:
#    - os: linux
#      sudo: required
#      python: 3.4
#    - os: linux
#      sudo: required
#      python: 3.5
#      env: OS=linux
#    - os: osx
#      sudo: required
#      language: generic
#      env: PYVER=3.4
    - os: osx
      osx_image: xcode7.3
      sudo: required
      language: generic
      env:
        - OS=osx
        - PYVER=3.5

before_install:
  - which bash
  - sudo chmod +x .travis/install.sh && sudo chown $USER .travis/install.sh && /bin/bash .travis/install.sh

install:
  - python3 -m venv camsa-env
  - source camsa-env/bin/activate
  - which pip
  - pip install -r requirements.txt
  - chmod +x camsa/utils/mummer/nucmer-to-camsa.py

script: camsa/utils/mummer/nucmer-to-camsa.py --help
