language: python

matrix:
  include:
#    - os: linux
#      sudo: required
#      python: 3.4
    - os: linux
      sudo: required
      python: 3.5
      env: OS=linux
#    - os: osx
#      sudo: required
#      language: generic
#      env: PYVER=3.4
    - os: osx
      sudo: required
      language: generic
      env:
        - OS=osx
        - OS=PYVER=3.5

before_install: sudo chmod +x .travis/install.sh && sudo ./.travis/install.sh

install:
  - python3 -m venv camsa-env
  - source camsa-env/bin/activate
  - sudo /camsa-env/bin/pip install -r requirements.txt
  - chmod +x camsa/utils/mummer/nucmer-to-camsa.py

script: camsa/utils/mummer/nucmer-to-camsa.py --help
