language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
#  - pypy
#  - pypy3
os:
  - linux
sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PYTHON=3.3
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PYTHON=3.4
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PYTHON=3.5
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PYTHON=2.7
#    - os: osx
#      osx_image: xcode7.3
#      language: generic
#      env:
#        - PYTHON=pypy.2
#    - os: osx
#      osx_image: xcode7.3
#      language: generic
#      env:
#        - PYTHON=pypy.3

before_install:
  - sudo chmod +x .travis/install.sh && sudo chown $USER .travis/install.sh && /bin/bash .travis/install.sh

install:
  - source camsa-env/bin/activate
  - pip install -e .
  - pip install -e .[fasta]
#  - chmod +x camsa/utils/fasta/fasta2camsa_points.py
#  - chmod +x camsa/utils/fasta/fasta2camsa_lengths.py
#  - chmod +x camsa/run_camsa.py

script:
  - cd camsa/examples/utils/fasta/data
  - gzip -d B_anthracis_contigs.fasta.gz B_anthracis_Mslice.fasta.gz
  - cd ../../../../../
  - camsa-env/bin/fasta2camsa_points.py --help
  - camsa-env/bin/fasta2camsa_points.py --nucmer-path `which nucmer` --show-coords-path `which show-coords` camsa/examples/utils/fasta/data/B_anthracis_contigs.fasta camsa/examples/utils/fasta/data/B_anthracis_Mslice.fasta --output-dir camsa/examples/utils/fasta/data/output
  - camsa-env/bin/fasta2camsa_lengths.py --help
  - camsa-env/bin/fasta2camsa_lengths.py camsa/examples/utils/fasta/data/B_anthracis_contigs.fasta -o camsa/examples/utils/fasta/data/output/B_anthracis_contigs.camsa.lengths
  - camsa-env/bin/run_camsa.py --help
  - camsa-env/bin/run_camsa.py camsa/examples/utils/fasta/data/output/B_anthracis_Mslice.camsa.points -o camsa/examples/B_antracis
