language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
#  - pypy
#  - pypy3
os:
  - linux
sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PYTHON=3.3
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PYTHON=3.4
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PYTHON=3.5
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PYTHON=2.7

before_install:
  - sudo chmod +x .travis/install.sh && sudo chown $USER .travis/install.sh && /bin/bash .travis/install.sh

install:
  - source camsa-env/bin/activate
  - pip install -e .
  - pip install -e .[fasta]

script:
  - cd camsa/examples/utils/fasta/data
  - gzip -d B_anthracis_contigs.fasta.gz B_anthracis_Mslice.fasta.gz
  - cd ../../../../../
  - fasta2camsa_points.py --nucmer-path `which nucmer` --show-coords-path `which show-coords` camsa/examples/utils/fasta/data/B_anthracis_contigs.fasta camsa/examples/utils/fasta/data/B_anthracis_Mslice.fasta --output-dir camsa/examples/utils/fasta/data/output
  - mkdir camsa/examples/utils/agp/output
  - fasta2camsa_lengths.py camsa/examples/utils/fasta/data/B_anthracis_contigs.fasta -o camsa/examples/utils/fasta/output/B_anthracis_contigs.camsa.lengths
  - agp2fasta_points.py camsa/examples/utils/agp/data/chr_from_component_wgs.agp -o camsa/examples/utils/agp/output/chr_from_component_wgs.camsa.points
  - agp2fasta_points.py camsa/examples/utils/agp/data/chr_from_scaffold_wgs.agp -o camsa/examples/utils/agp/output/chr_from_scaffold_wgs.camsa.points
  - agp2fasta_points.py camsa/examples/utils/agp/data/scaffold_from_contig_wgs.agp -o camsa/examples/utils/agp/output/scaffold_from_contig_wgs.camsa.points
  - run_camsa.py camsa/examples/utils/fasta/output/B_anthracis_Mslice.camsa.points -o camsa/examples/B_antracis_Mslice
  - run_camsa.py camsa/examples/gage/exp1/sga.camsa.points camsa/examples/gage/exp1/sspace.camsa.points camsa/examples/gage/exp1/soap2.camsa.points camsa/examples/gage/exp1/scaffmatch.camsa.points -o camsa/examples/B_antracis
  - run_camsa.py camsa/examples/gage/exp1/sga.camsa.points camsa/examples/gage/exp1/sspace.camsa.points camsa/examples/gage/exp1/soap2.camsa.points camsa/examples/gage/exp1/scaffmatch.camsa.points -o camsa/examples/gage/exp1/output
  - run_camsa.py camsa/examples/gage/exp1/sga.camsa.points camsa/examples/gage/exp1/sspace.camsa.points camsa/examples/gage/exp1/soap2.camsa.points camsa/examples/gage/exp1/scaffmatch.camsa.points -o camsa/examples/gage/exp2/output

