language: python
python:
  - 2.7
  - 3.5
  - 3.6

os:
  - linux
sudo: required

matrix:
  include:
        - python: 3.7
          dist: xenial
          sudo: true

        - os: osx
          osx_image: xcode9.4
          language: generic
          env:
          - PYTHON=2.7
        - os: osx
          osx_image: xcode9.4
          language: generic
          env:
          - PYTHON=3.5
        - os: osx
          osx_image: xcode9.4
          language: generic
          env:
          - PYTHON=3.6
        - os: osx
          osx_image: xcode9.4
          language: generic
          env:
          - PYTHON=3.7

before_install:
  - sudo chmod +x .travis/install.sh && sudo chown $USER .travis/install.sh && /bin/bash .travis/install.sh

install:
  - conda list
  - export PATH="$HOME/miniconda/bin:$PATH"
  - echo $PATH
  - ls -lh ~/miniconda/bin/
  - nucmer -h
  - travis_wait 30 pip install -e .

script:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - nucmer -h
  - cd camsa/examples/utils/fasta/data
  - gzip -d B_anthracis_contigs.fasta.gz B_anthracis_Mslice.fasta.gz
  - cd ../../../../../
  - cd camsa/examples/gage/exp1
  - gzip -d contigs.fasta.gz
  - cd ../exp2
  - gzip -d contigs.fasta.gz
  - cd ../../../../
  # B_antracis_Mslice fasta files used in nucmer documentation as an example
  - fasta2camsa_points.py camsa/examples/utils/fasta/data/B_anthracis_contigs.fasta camsa/examples/utils/fasta/data/B_anthracis_Mslice.fasta --output-dir camsa/examples/utils/fasta/output
  - mkdir camsa/examples/utils/agp/output
  - fasta2camsa_seqi.py camsa/examples/utils/fasta/data/B_anthracis_contigs.fasta -o camsa/examples/utils/fasta/output/B_anthracis_contigs.camsa.seqi
  - run_camsa.py camsa/examples/utils/fasta/output/B_anthracis_Mslice.camsa.points -o camsa/examples/B_antracis_Mslice

  # AGPv2.0 conversion test section
  - agp2camsa_points.py camsa/examples/utils/agp/data/chr_from_component_wgs.agp -o camsa/examples/utils/agp/output/chr_from_component_wgs.camsa.points
  - agp2camsa_points.py camsa/examples/utils/agp/data/chr_from_scaffold_wgs.agp -o camsa/examples/utils/agp/output/chr_from_scaffold_wgs.camsa.points
  - agp2camsa_points.py camsa/examples/utils/agp/data/scaffold_from_contig_wgs.agp -o camsa/examples/utils/agp/output/scaffold_from_contig_wgs.camsa.points

  # GAGE experiment 1 (S. aureus)
  - run_camsa.py camsa/examples/gage/exp1/sga.camsa.points camsa/examples/gage/exp1/sspace.camsa.points camsa/examples/gage/exp1/soap2.camsa.points camsa/examples/gage/exp1/scaffmatch.camsa.points -o camsa/examples/gage/exp1/scaffolders
  - camsa_points2fasta.py --points camsa/examples/gage/exp1/scaffolders/merged/merged.camsa.points --fasta camsa/examples/gage/exp1/contigs.fasta -o camsa/examples/gage/exp1/scaffolders/merged/camsa.fasta

  - run_camsa.py camsa/examples/gage/exp1/sga.camsa.points camsa/examples/gage/exp1/sspace.camsa.points camsa/examples/gage/exp1/soap2.camsa.points camsa/examples/gage/exp1/scaffmatch.camsa.points camsa/examples/gage/exp1/metassembler.camsa.points camsa/examples/gage/exp1/gam-ngs.camsa.points -o camsa/examples/gage/exp1/scaffolders_gm
  - camsa_points2fasta.py --points camsa/examples/gage/exp1/scaffolders_gm/merged/merged.camsa.points --fasta camsa/examples/gage/exp1/contigs.fasta -o camsa/examples/gage/exp1/scaffolders_gm/merged/camsa.fasta

  # GAGE experiment 2 (R. sphaeroides)
  - run_camsa.py camsa/examples/gage/exp2/sga.camsa.points camsa/examples/gage/exp2/sspace.camsa.points camsa/examples/gage/exp2/soap2.camsa.points camsa/examples/gage/exp2/scaffmatch.camsa.points -o camsa/examples/gage/exp2/scaffolders
  - camsa_points2fasta.py --points camsa/examples/gage/exp2/scaffolders/merged/merged.camsa.points --fasta camsa/examples/gage/exp2/contigs.fasta -o camsa/examples/gage/exp2/scaffolders/merged/camsa.fasta

  - run_camsa.py camsa/examples/gage/exp2/sga.camsa.points camsa/examples/gage/exp2/sspace.camsa.points camsa/examples/gage/exp2/soap2.camsa.points camsa/examples/gage/exp2/scaffmatch.camsa.points camsa/examples/gage/exp2/metassembler.camsa.points camsa/examples/gage/exp2/gam-ngs.camsa.points -o camsa/examples/gage/exp2/scaffolders_gm
  - camsa_points2fasta.py --points camsa/examples/gage/exp2/scaffolders_gm/merged/merged.camsa.points --fasta camsa/examples/gage/exp2/contigs.fasta -o camsa/examples/gage/exp2/scaffolders_gm/merged/camsa.fasta

  # GAGE experiment 3 (H. sapiens chr14)
  - run_camsa.py camsa/examples/gage/exp3/sga.camsa.points camsa/examples/gage/exp3/sspace.camsa.points camsa/examples/gage/exp3/soap2.camsa.points camsa/examples/gage/exp3/scaffmatch.camsa.points -o camsa/examples/gage/exp3/scaffolders
  - run_camsa.py camsa/examples/gage/exp3/sga.camsa.points camsa/examples/gage/exp3/sspace.camsa.points camsa/examples/gage/exp3/soap2.camsa.points camsa/examples/gage/exp3/scaffmatch.camsa.points camsa/examples/gage/exp3/metassembler.camsa.points camsa/examples/gage/exp3/gam-ngs.camsa.points -o camsa/examples/gage/exp3/scaffolders_gm

